### ISSUE TITLE
[Enhancement] Schema directly references index signature alias name

### ISSUE THREAD

**Issue by Peefy** [KusionStack/kcl#577]
## Enhancement

Currently, the index signature alias can be used in the schema check block, but it cannot be used in the schema body yet. We need to support it and maintain consistency

### Example 1

Input:

```python
schema TeamSpec[id: str]:
    fullName: str
    name = id
    shortName: str = name

schema TeamMap:
    [n: str]: TeamSpec = TeamSpec(n)  # `n` does not work currently

Team = TeamMap {
    a.fullName = "alpha"
    b.fullName = "bravo"
}
```

Output

```yaml
Team:
  a:
    fullName: alpha
    name: a
    shortName: a
  b:
    fullName: bravo
    name: b
    shortName: b
```
